version: '0.0.1'
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: inventrohyder/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: inventrohyder/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: inventrohyder/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: inventrohyder/udagram-frontend
