version: '0.0.1'
services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend_user
      - backend_feed
  backend_user:
    image: udagram-api-user
    environment:
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - AWS_BUCKET=$AWS_BUCKET
      - AWS_REGION=$AWS_REGION
      - AWS_PROFILE=$AWS_PROFILE
      - JWT_SECRET=$JWT_SECRET
      - URL=$URL
  backend_feed:
    volumes:
      - $HOME/.aws:/root/.aws
    image: udagram-api-feed
    environment:
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - AWS_BUCKET=$AWS_BUCKET
      - AWS_REGION=$AWS_REGION
      - AWS_PROFILE=$AWS_PROFILE
      - JWT_SECRET=$JWT_SECRET
      - URL=$URL
  frontend:
    image: udagram-frontend:local
    ports:
      - 8100:80
