apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  selector:
    app: backend-user
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: backend-feed
spec:
  selector:
    app: backend-feed
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  selector:
    app: reverseproxy
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8100
      targetPort: 80
